//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdminContext : DbContext
    {
        public AdminContext()
            : base("name=AdminContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aloAlojamiento> aloAlojamientos { get; set; }
        public virtual DbSet<aloExcepcione> aloExcepciones { get; set; }
        public virtual DbSet<aloReserva> aloReservas { get; set; }
        public virtual DbSet<aloSorteo> aloSorteos { get; set; }
        public virtual DbSet<aloTipos> aloTipos { get; set; }
        public virtual DbSet<aloZona> aloZonas { get; set; }
        public virtual DbSet<autUsuario> autUsuarios { get; set; }
        public virtual DbSet<appBus> appBuses { get; set; }
        public virtual DbSet<appChofere> appChoferes { get; set; }
        public virtual DbSet<appEstacione> appEstaciones { get; set; }
        public virtual DbSet<appParada> appParadas { get; set; }
        public virtual DbSet<appPromocione> appPromociones { get; set; }
        public virtual DbSet<appRuta> appRutas { get; set; }
        public virtual DbSet<genActividade> genActividades { get; set; }
        public virtual DbSet<genTicketsVenta> genTicketsVentas { get; set; }
        public virtual DbSet<genTicketsZona> genTicketsZonas { get; set; }
        public virtual DbSet<genTransaccionesVisanet> genTransaccionesVisanets { get; set; }
    }
}
