//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aloExcepciones
    {
        public int Id { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public System.DateTime desde { get; set; }
        public System.DateTime hasta { get; set; }
        public short porcentaje { get; set; }
        public string tipoExcep { get; set; }
        public int tipo_Id { get; set; }
    
        public virtual aloTipos aloTipos { get; set; }
    }
}
