//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aloReserva
    {
        public int Id { get; set; }
        public System.DateTime fecha { get; set; }
        public System.DateTime fechaEntrada { get; set; }
        public System.DateTime fechaSalida { get; set; }
        public string codigoReserva { get; set; }
        public string comentarios { get; set; }
        public string DEUCON { get; set; }
        public string DEUPRV { get; set; }
        public double monto { get; set; }
        public double IGV { get; set; }
        public double total { get; set; }
        public string alojamiento_Id { get; set; }
        public string gestor_Id { get; set; }
        public string socio_Id { get; set; }
        public bool confirmada { get; set; }
        public string emision { get; set; }
    
        public virtual aloAlojamiento aloAlojamiento { get; set; }
        public virtual autUsuario autUsuario { get; set; }
        public virtual autUsuario autUsuario1 { get; set; }
    }
}
