//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aloReservas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public aloReservas()
        {
            this.aloSorteoInscrip = new HashSet<aloSorteoInscrip>();
        }
    
        public int Id { get; set; }
        public System.DateTime fecha { get; set; }
        public System.DateTime fechaEntrada { get; set; }
        public System.DateTime fechaSalida { get; set; }
        public string codigoReserva { get; set; }
        public string comentarios { get; set; }
        public string DEUCON { get; set; }
        public string DEUPRV { get; set; }
        public double monto { get; set; }
        public double IGV { get; set; }
        public double total { get; set; }
        public bool confirmada { get; set; }
        public int alojamiento_Id { get; set; }
        public string gestor_Id { get; set; }
        public string socio_Id { get; set; }
        public string emision { get; set; }
        public Nullable<int> carnet { get; set; }
    
        public virtual aloAlojamientos aloAlojamientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aloSorteoInscrip> aloSorteoInscrip { get; set; }
        public virtual autUsuarios autUsuarios { get; set; }
        public virtual autUsuarios autUsuarios1 { get; set; }
    }
}
