//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aloSorteos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public aloSorteos()
        {
            this.aloSorteoInscrip = new HashSet<aloSorteoInscrip>();
        }
    
        public int Id { get; set; }
        public string detalle { get; set; }
        public System.DateTime fecha { get; set; }
        public System.DateTime fechaPago { get; set; }
        public System.DateTime estadia_desde { get; set; }
        public System.DateTime estadia_hasta { get; set; }
        public System.DateTime inscripcion_desde { get; set; }
        public System.DateTime inscripcion_hasta { get; set; }
        public Nullable<int> tipo_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aloSorteoInscrip> aloSorteoInscrip { get; set; }
        public virtual aloTipos aloTipos { get; set; }
    }
}
