//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aloTipos
    {
        public aloTipos()
        {
            this.aloAlojamientos = new HashSet<aloAlojamiento>();
            this.aloExcepciones = new HashSet<aloExcepcione>();
            this.aloSorteos = new HashSet<aloSorteo>();
            this.aloZonas = new HashSet<aloZona>();
        }
    
        public int Id { get; set; }
        public string nombre { get; set; }
        public System.DateTime inicioTempAlta { get; set; }
        public System.DateTime finTempAlta { get; set; }
        public string clase { get; set; }
        public string croquis { get; set; }
        public double precioTempAlta { get; set; }
        public double precioTempBaja { get; set; }
        public string idSede { get; set; }
        public bool restricFDStempAlta { get; set; }
    
        public virtual ICollection<aloAlojamiento> aloAlojamientos { get; set; }
        public virtual ICollection<aloExcepcione> aloExcepciones { get; set; }
        public virtual ICollection<aloSorteo> aloSorteos { get; set; }
        public virtual ICollection<aloZona> aloZonas { get; set; }
    }
}
