//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aloZona
    {
        public aloZona()
        {
            this.aloAlojamientos = new HashSet<aloAlojamiento>();
        }
    
        public string Id { get; set; }
        public string desc1 { get; set; }
        public string desc2 { get; set; }
        public int personas { get; set; }
        public string croquis { get; set; }
        public double precio { get; set; }
        public Nullable<int> tipo_Id { get; set; }
    
        public virtual ICollection<aloAlojamiento> aloAlojamientos { get; set; }
        public virtual aloTipos aloTipos { get; set; }
    }
}
