//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aloZonas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public aloZonas()
        {
            this.aloAlojamientos = new HashSet<aloAlojamientos>();
        }
    
        public string Id { get; set; }
        public string desc1 { get; set; }
        public string desc2 { get; set; }
        public int personas { get; set; }
        public string croquis { get; set; }
        public string foto { get; set; }
        public Nullable<double> precioTempAlta { get; set; }
        public Nullable<double> precioTempBaja { get; set; }
        public Nullable<int> tipo_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aloAlojamientos> aloAlojamientos { get; set; }
        public virtual aloTipos aloTipos { get; set; }
    }
}
