//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aloZonas
    {
        public string Id { get; set; }
        public string desc1 { get; set; }
        public string desc2 { get; set; }
        public int personas { get; set; }
        public string croquis { get; set; }
        public string foto { get; set; }
        public Nullable<double> precioTempAlta { get; set; }
        public Nullable<double> precioTempBaja { get; set; }
        public int tipo_Id { get; set; }
    }
}
