//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class appChofere
    {
        public appChofere()
        {
            this.appRutas = new HashSet<appRuta>();
        }
    
        public int Id { get; set; }
        public string nombre { get; set; }
        public string foto { get; set; }
        public byte[] Version { get; set; }
        public System.DateTimeOffset CreatedAt { get; set; }
        public Nullable<System.DateTimeOffset> UpdatedAt { get; set; }
        public bool Deleted { get; set; }
        public string lic { get; set; }
    
        public virtual ICollection<appRuta> appRutas { get; set; }
    }
}
