//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class appParadas
    {
        public int Id { get; set; }
        public string nombre { get; set; }
        public int hora { get; set; }
        public int min { get; set; }
        public int duracion { get; set; }
        public bool esRetorno { get; set; }
        public byte[] Version { get; set; }
        public System.DateTimeOffset CreatedAt { get; set; }
        public Nullable<System.DateTimeOffset> UpdatedAt { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> estacion_Id { get; set; }
        public Nullable<int> ruta_Id { get; set; }
        public int currHora { get; set; }
        public int currMin { get; set; }
        public int estDuracion { get; set; }
    
        public virtual appEstaciones appEstaciones { get; set; }
    }
}
