//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class appPromociones
    {
        public int Id { get; set; }
        public string desc { get; set; }
        public string detalle { get; set; }
        public string marca { get; set; }
        public int nroCupones { get; set; }
        public string foto { get; set; }
        public string email { get; set; }
        public string tel { get; set; }
        public string direccion { get; set; }
        public System.DateTime desde { get; set; }
        public System.DateTime hasta { get; set; }
        public int sexo { get; set; }
        public int edadMax { get; set; }
        public int edadMin { get; set; }
        public int tipoAsociado { get; set; }
        public byte[] Version { get; set; }
        public System.DateTimeOffset CreatedAt { get; set; }
        public Nullable<System.DateTimeOffset> UpdatedAt { get; set; }
        public bool Deleted { get; set; }
    }
}
