//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class appRutas
    {
        public appRuta()
        {
            this.appParadas = new HashSet<appParada>();
            CreatedAt = DateTimeOffset.Now;
            lastBoard = DateTime.Today;
            activa = false;
            Deleted = false;
        }
    
        public int Id { get; set; }
        public string nombre { get; set; }
        public string descrip { get; set; }
        public string dias { get; set; }
        public bool activa { get; set; }
        public byte[] Version { get; set; }
        public System.DateTimeOffset CreatedAt { get; set; }
        public Nullable<System.DateTimeOffset> UpdatedAt { get; set; }
        public bool Deleted { get; set; }
        public double currLat { get; set; }
        public double currLon { get; set; }
        public System.DateTime lastBoard { get; set; }
        public Nullable<int> currBus_Id { get; set; }
        public Nullable<int> currChofer_Id { get; set; }
    
        public virtual appBuses appBuses { get; set; }
        public virtual appChoferes appChoferes { get; set; }
    }
}
