//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class genActividades
    {
        public int id { get; set; }
        public string desc { get; set; }
        public string detalle { get; set; }
        public string idSede { get; set; }
        public string lugar { get; set; }
        public System.DateTime fecha { get; set; }
        public string foto { get; set; }
        public string tel { get; set; }
        public string mail { get; set; }
        public bool ventaTickets { get; set; }
        public string blogPost { get; set; }
        public string refCosto { get; set; }
        public System.DateTime ventaDesde { get; set; }
        public System.DateTime ventaHasta { get; set; }
    }
}
