//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class genTicketsVentas
    {
        public string idEntrada { get; set; }
        public int cantidad_real { get; set; }
        public int cantidad { get; set; }
        public double unitario { get; set; }
        public System.DateTime fecha { get; set; }
        public string concepto { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string tipoDoc { get; set; }
        public string numDoc { get; set; }
        public string tel { get; set; }
        public string email { get; set; }
        public string numeracion { get; set; }
        public bool confirmada { get; set; }
        public bool cargoCuenta { get; set; }
        public Nullable<int> pagoOnline_Id { get; set; }
        public string socio_Id { get; set; }
        public Nullable<int> zona_id { get; set; }
        public int idPrecio { get; set; }
    
        public virtual autUsuarios autUsuarios { get; set; }
        public virtual genTicketsZonas genTicketsZonas { get; set; }
        public virtual genTransaccionesVisanet genTransaccionesVisanet { get; set; }
    }
}
