//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class genTicketsZona
    {
        public genTicketsZona()
        {
            this.genTicketsVentas = new HashSet<genTicketsVenta>();
        }
    
        public int id { get; set; }
        public string desc { get; set; }
        public double precio { get; set; }
        public int cupos { get; set; }
        public int vendidos { get; set; }
        public string croquis { get; set; }
        public int porcSobreventa { get; set; }
        public int actividad_id { get; set; }
    
        public virtual genActividade genActividade { get; set; }
        public virtual ICollection<genTicketsVenta> genTicketsVentas { get; set; }
    }
}
