//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class genTransaccionesVisanet
    {
        public genTransaccionesVisanet()
        {
            this.genTicketsVentas = new HashSet<genTicketsVenta>();
        }
    
        public int Id { get; set; }
        public double monto { get; set; }
        public string email { get; set; }
        public string codConcepto { get; set; }
        public string concepto { get; set; }
        public System.DateTime fecha { get; set; }
        public int status { get; set; }
        public string digitosCC { get; set; }
        public byte[] Version { get; set; }
        public System.DateTimeOffset CreatedAt { get; set; }
        public Nullable<System.DateTimeOffset> UpdatedAt { get; set; }
        public bool Deleted { get; set; }
        public string socio_Id { get; set; }
        public string ticket { get; set; }
        public string resultadoOp { get; set; }
        public string estado { get; set; }
    
        public virtual autUsuario autUsuario { get; set; }
        public virtual ICollection<genTicketsVenta> genTicketsVentas { get; set; }
    }
}
