//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class genTicketsPreciosEsp
    {
        public int id { get; set; }
        public string desc { get; set; }
        public double precio { get; set; }
        public int cantidad { get; set; }
        public int zona_id { get; set; }
    
        public virtual genTicketsZonas genTicketsZonas { get; set; }
    }
}
