//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAdminMvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdminContext : DbContext
    {
        public AdminContext()
            : base("name=AdminContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aloAlojamientos> aloAlojamientos { get; set; }
        public virtual DbSet<aloExcepciones> aloExcepciones { get; set; }
        public virtual DbSet<aloReservas> aloReservas { get; set; }
        public virtual DbSet<aloSorteoInscrip> aloSorteoInscrip { get; set; }
        public virtual DbSet<aloSorteos> aloSorteos { get; set; }
        public virtual DbSet<aloTipos> aloTipos { get; set; }
        public virtual DbSet<aloZonas> aloZonas { get; set; }
        public virtual DbSet<appBuses> appBuses { get; set; }
        public virtual DbSet<appChoferes> appChoferes { get; set; }
        public virtual DbSet<appEstaciones> appEstaciones { get; set; }
        public virtual DbSet<appParadas> appParadas { get; set; }
        public virtual DbSet<appPromociones> appPromociones { get; set; }
        public virtual DbSet<appRutas> appRutas { get; set; }
        public virtual DbSet<autUsuarios> autUsuarios { get; set; }
        public virtual DbSet<genActividades> genActividades { get; set; }
        public virtual DbSet<genTicketsPreciosEsp> genTicketsPreciosEsp { get; set; }
        public virtual DbSet<genTicketsVentas> genTicketsVentas { get; set; }
        public virtual DbSet<genTicketsZonas> genTicketsZonas { get; set; }
        public virtual DbSet<genTransaccionesVisanet> genTransaccionesVisanet { get; set; }
    }
}
